baseURL = 'https://cemehbl4.github.io/wiki/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'relearn'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup.goldmark.renderer]
unsafe = true
