baseURL = 'https://crypto-warz.github.io/wiki/'
languageCode = 'en-us'
title = 'CryptoWarz'
theme = 'relearn'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup.goldmark.renderer]
unsafe = true
