baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'relearn'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup.goldmark.renderer]
unsafe = true
